<a href="https://colab.research.google.com/github/Deepikakalimuthu/data_analytics_project/blob/main/project4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
import pandas as pd
df=pd.read_csv("/content/credit_risk_dataset.csv")

In [ ]:
!pip install pandas

In [ ]:
!pip install numpy

In [ ]:
!pip install matplotlib
!pip install seaborn

In [ ]:
!pip install scikit-learn

In [ ]:
import pandas as pd
df=pd.read_csv("/content/credit_risk_dataset.csv")

In [ ]:
df

person_age  person_income person_home_ownership  person_emp_length  \
0              22          59000                  RENT              123.0   
1              21           9600                   OWN                5.0   
2              25           9600              MORTGAGE                1.0   
3              23          65500                  RENT                4.0   
4              24          54400                  RENT                8.0   
...           ...            ...                   ...                ...   
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32578          65          76000                  RENT                3.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0             PERSONAL          D      35000          16.02            1   
1            EDUCATION          B       1000          11.14            0   
2              MEDICAL          C       5500          12.87            1   
3              MEDICAL          C      35000          15.23            1   
4              MEDICAL          C      35000          14.27            1   
...                ...        ...        ...            ...          ...   
32576         PERSONAL          C       5800          13.16            0   
32577         PERSONAL          A      17625           7.49            0   
32578  HOMEIMPROVEMENT          B      35000          10.99            1   
32579         PERSONAL          B      15000          11.48            0   
32580          MEDICAL          B       6475           9.99            0   

       loan_percent_income cb_person_default_on_file  \
0                     0.59                         Y   
1                     0.10                         N   
2                     0.57                         N   
3                     0.53                         N   
4                     0.55                         Y   
...                    ...                       ...   
32576                 0.11                         N   
32577                 0.15                         N   
32578                 0.46                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  
0                               3  
1                               2  
2                               3  
3                               2  
4                               4  
...                           ...  
32576                          30  
32577                          19  
32578                          28  
32579                          26  
32580                          30  

[32581 rows x 12 columns]

In [ ]:
df.isnull()

person_age  person_income  person_home_ownership  person_emp_length  \
0           False          False                  False              False   
1           False          False                  False              False   
2           False          False                  False              False   
3           False          False                  False              False   
4           False          False                  False              False   
...           ...            ...                    ...                ...   
32576       False          False                  False              False   
32577       False          False                  False              False   
32578       False          False                  False              False   
32579       False          False                  False              False   
32580       False          False                  False              False   

       loan_intent  loan_grade  loan_amnt  loan_int_rate  loan_status  \
0            False       False      False          False        False   
1            False       False      False          False        False   
2            False       False      False          False        False   
3            False       False      False          False        False   
4            False       False      False          False        False   
...            ...         ...        ...            ...          ...   
32576        False       False      False          False        False   
32577        False       False      False          False        False   
32578        False       False      False          False        False   
32579        False       False      False          False        False   
32580        False       False      False          False        False   

       loan_percent_income  cb_person_default_on_file  \
0                    False                      False   
1                    False                      False   
2                    False                      False   
3                    False                      False   
4                    False                      False   
...                    ...                        ...   
32576                False                      False   
32577                False                      False   
32578                False                      False   
32579                False                      False   
32580                False                      False   

       cb_person_cred_hist_length  
0                           False  
1                           False  
2                           False  
3                           False  
4                           False  
...                           ...  
32576                       False  
32577                       False  
32578                       False  
32579                       False  
32580                       False  

[32581 rows x 12 columns]

In [ ]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(4011)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   person_age                  32581 non-null  int64  
 1   person_income               32581 non-null  int64  
 2   person_home_ownership       32581 non-null  object 
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object 
 5   loan_grade                  32581 non-null  object 
 6   loan_amnt                   32581 non-null  int64  
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64  
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object 
 11  cb_person_cred_hist_length  32581 non-null  int64  
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB


In [ ]:
df.shape

(32581, 12)

In [ ]:
df['loan_status']

0        1
1        0
2        1
3        1
4        1
        ..
32576    0
32577    0
32578    1
32579    0
32580    0
Name: loan_status, Length: 32581, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(165)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dtypes

person_age                      int64
person_income                   int64
person_home_ownership          object
person_emp_length             float64
loan_intent                    object
loan_grade                     object
loan_amnt                       int64
loan_int_rate                 float64
loan_status                     int64
loan_percent_income           float64
cb_person_default_on_file      object
cb_person_cred_hist_length      int64
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['person_home_ownership']=le.fit_transform(df['person_home_ownership'])
df['loan_intent']=le.fit_transform(df['loan_intent'])
df['loan_grade']=le.fit_transform(df['loan_grade'])
df['cb_person_default_on_file']=le.fit_transform(df['cb_person_default_on_file'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32416 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   person_age                  32416 non-null  int64  
 1   person_income               32416 non-null  int64  
 2   person_home_ownership       32416 non-null  int64  
 3   person_emp_length           31529 non-null  float64
 4   loan_intent                 32416 non-null  int64  
 5   loan_grade                  32416 non-null  int64  
 6   loan_amnt                   32416 non-null  int64  
 7   loan_int_rate               29321 non-null  float64
 8   loan_status                 32416 non-null  int64  
 9   loan_percent_income         32416 non-null  float64
 10  cb_person_default_on_file   32416 non-null  int64  
 11  cb_person_cred_hist_length  32416 non-null  int64  
dtypes: float64(3), int64(9)
memory usage: 3.2 MB


In [ ]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              887
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3095
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [ ]:
df['person_emp_length']=df['person_emp_length'].fillna(df['person_emp_length'].median())
df['loan_int_rate']=df['loan_int_rate'].fillna(df['loan_int_rate'].median())
df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [ ]:
x=df.drop(["loan_status"],axis=1)
y=df["loan_status"]
x

person_age  person_income  person_home_ownership  person_emp_length  \
0              22          59000                      3              123.0   
1              21           9600                      2                5.0   
2              25           9600                      0                1.0   
3              23          65500                      3                4.0   
4              24          54400                      3                8.0   
...           ...            ...                    ...                ...   
32576          57          53000                      0                1.0   
32577          54         120000                      0                4.0   
32578          65          76000                      3                3.0   
32579          56         150000                      0                5.0   
32580          66          42000                      3                2.0   

       loan_intent  loan_grade  loan_amnt  loan_int_rate  loan_percent_income  \
0                4           3      35000          16.02                 0.59   
1                1           1       1000          11.14                 0.10   
2                3           2       5500          12.87                 0.57   
3                3           2      35000          15.23                 0.53   
4                3           2      35000          14.27                 0.55   
...            ...         ...        ...            ...                  ...   
32576            4           2       5800          13.16                 0.11   
32577            4           0      17625           7.49                 0.15   
32578            2           1      35000          10.99                 0.46   
32579            4           1      15000          11.48                 0.10   
32580            3           1       6475           9.99                 0.15   

       cb_person_default_on_file  cb_person_cred_hist_length  
0                              1                           3  
1                              0                           2  
2                              0                           3  
3                              0                           2  
4                              1                           4  
...                          ...                         ...  
32576                          0                          30  
32577                          0                          19  
32578                          0                          28  
32579                          0                          26  
32580                          0                          30  

[32416 rows x 11 columns]

In [ ]:
y

0        1
1        0
2        1
3        1
4        1
        ..
32576    0
32577    0
32578    1
32579    0
32580    0
Name: loan_status, Length: 32416, dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
c=sc.fit_transform(x)
print(c)

[[1.61290323e-02 9.17278185e-03 1.00000000e+00 ... 7.10843373e-01
  1.00000000e+00 3.57142857e-02]
 [8.06451613e-03 9.33955971e-04 6.66666667e-01 ... 1.20481928e-01
  0.00000000e+00 0.00000000e+00]
 [4.03225806e-02 9.33955971e-04 0.00000000e+00 ... 6.86746988e-01
  0.00000000e+00 3.57142857e-02]
 ...
 [3.62903226e-01 1.20080053e-02 1.00000000e+00 ... 5.54216867e-01
  0.00000000e+00 9.28571429e-01]
 [2.90322581e-01 2.43495664e-02 0.00000000e+00 ... 1.20481928e-01
  0.00000000e+00 8.57142857e-01]
 [3.70967742e-01 6.33755837e-03 1.00000000e+00 ... 1.80722892e-01
  0.00000000e+00 1.00000000e+00]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
from sklearn.linear_model import LogisticRegression  #LinearRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

(25932, 11)
(6484, 11)
(25932,)
(6484,)


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8235657001850709
[[4841  232]
 [ 912  499]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      5073
           1       0.68      0.35      0.47      1411

    accuracy                           0.82      6484
   macro avg       0.76      0.65      0.68      6484
weighted avg       0.81      0.82      0.80      6484



In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report  #r2_score
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8232572486119679
[[4844  229]
 [ 917  494]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      5073
           1       0.68      0.35      0.46      1411

    accuracy                           0.82      6484
   macro avg       0.76      0.65      0.68      6484
weighted avg       0.81      0.82      0.80      6484



/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8861813695249846
[[4661  412]
 [ 326 1085]]
              precision    recall  f1-score   support

           0       0.93      0.92      0.93      5073
           1       0.72      0.77      0.75      1411

    accuracy                           0.89      6484
   macro avg       0.83      0.84      0.84      6484
weighted avg       0.89      0.89      0.89      6484



In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_test,y_test)
y_pred=dt.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[5073    0]
 [   0 1411]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5073
           1       1.00      1.00      1.00      1411

    accuracy                           1.00      6484
   macro avg       1.00      1.00      1.00      6484
weighted avg       1.00      1.00      1.00      6484



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.932449105490438
[[5041   32]
 [ 406 1005]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      5073
           1       0.97      0.71      0.82      1411

    accuracy                           0.93      6484
   macro avg       0.95      0.85      0.89      6484
weighted avg       0.93      0.93      0.93      6484



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_test,y_test)
y_pred=rf.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[5073    0]
 [   0 1411]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5073
           1       1.00      1.00      1.00      1411

    accuracy                           1.00      6484
   macro avg       1.00      1.00      1.00      6484
weighted avg       1.00      1.00      1.00      6484



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8349784083898828
[[4709  364]
 [ 706  705]]
              precision    recall  f1-score   support

           0       0.87      0.93      0.90      5073
           1       0.66      0.50      0.57      1411

    accuracy                           0.83      6484
   macro avg       0.76      0.71      0.73      6484
weighted avg       0.82      0.83      0.83      6484



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_test,y_test)
y_pred=knn.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8693707587908698
[[4835  238]
 [ 609  802]]
              precision    recall  f1-score   support

           0       0.89      0.95      0.92      5073
           1       0.77      0.57      0.65      1411

    accuracy                           0.87      6484
   macro avg       0.83      0.76      0.79      6484
weighted avg       0.86      0.87      0.86      6484



In [ ]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8067550894509562
[[5024   49]
 [1204  207]]
              precision    recall  f1-score   support

           0       0.81      0.99      0.89      5073
           1       0.81      0.15      0.25      1411

    accuracy                           0.81      6484
   macro avg       0.81      0.57      0.57      6484
weighted avg       0.81      0.81      0.75      6484



In [ ]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_test,y_test)
y_pred=svc.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7823874151758174
[[5073    0]
 [1411    0]]
              precision    recall  f1-score   support

           0       0.78      1.00      0.88      5073
           1       0.00      0.00      0.00      1411

    accuracy                           0.78      6484
   macro avg       0.39      0.50      0.44      6484
weighted avg       0.61      0.78      0.69      6484



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8180135718692165
[[4776  297]
 [ 883  528]]
              precision    recall  f1-score   support

           0       0.84      0.94      0.89      5073
           1       0.64      0.37      0.47      1411

    accuracy                           0.82      6484
   macro avg       0.74      0.66      0.68      6484
weighted avg       0.80      0.82      0.80      6484



In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_test,y_test)
y_pred=nb.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8246452806909316
[[4835  238]
 [ 899  512]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      5073
           1       0.68      0.36      0.47      1411

    accuracy                           0.82      6484
   macro avg       0.76      0.66      0.68      6484
weighted avg       0.81      0.82      0.80      6484



In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.ensemble import RandomForestClassifier
model= RandomForestClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9309068476249229
[[5041   32]
 [ 416  995]]
              precision    recall  f1-score   support

           0       0.92      0.99      0.96      5073
           1       0.97      0.71      0.82      1411

    accuracy                           0.93      6484
   macro avg       0.95      0.85      0.89      6484
weighted avg       0.93      0.93      0.93      6484



In [ ]:
model=RandomForestClassifier()
model.fit(x_test,y_test)
y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[5073    0]
 [   0 1411]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5073
           1       1.00      1.00      1.00      1411

    accuracy                           1.00      6484
   macro avg       1.00      1.00      1.00      6484
weighted avg       1.00      1.00      1.00      6484



In [ ]:
rf_param={
    'n_estimators':[10,20,30,40,50,60,70,80,90,100],
    'max_depth':[1,2,3,4,5,6,7,8,9,10],
    'min_samples_split':[2,3,4,5,6,7,8,9,10],
    'min_samples_leaf':[1,2,3,4,5,6,7,8,9,10]
}
from sklearn.model_selection import RandomizedSearchCV
rf_model=RandomForestClassifier()
rf_cv=RandomizedSearchCV(rf_model,rf_param,cv=5)
rf_cv.fit(x_train,y_train)
rf_cv.best_params_

{'n_estimators': 90,
 'min_samples_split': 7,
 'min_samples_leaf': 7,
 'max_depth': 9}

In [ ]:
rf_param={
    'n_estimators':[10,20,30,40,50,60,70,80,90,100],
    'max_depth':[1,2,3,4,5,6,7,8,9,10],
    'min_samples_split':[2,3,4,5,6,7,8,9,10],
    'min_samples_leaf':[1,2,3,4,5,6,7,8,9,10]
}
from sklearn.model_selection import RandomizedSearchCV
rf_model=RandomForestClassifier()
rf_cv=RandomizedSearchCV(rf_model,rf_param,cv=5)
rf_cv.fit(x_train,y_train)
rf_cv.best_params_

{'n_estimators': 40,
 'min_samples_split': 3,
 'min_samples_leaf': 7,
 'max_depth': 10}

In [ ]:
rf_model=RandomForestClassifier(n_estimators=90,min_samples_split=7,min_samples_leaf=7,max_depth=9)
model=rf_model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9235040098704503
[[5050   23]
 [ 473  938]]
              precision    recall  f1-score   support

           0       0.91      1.00      0.95      5073
           1       0.98      0.66      0.79      1411

    accuracy                           0.92      6484
   macro avg       0.95      0.83      0.87      6484
weighted avg       0.93      0.92      0.92      6484



In [ ]:
rf_model=RandomForestClassifier(n_estimators=40,min_samples_split=3,min_samples_leaf=7,max_depth=10)
model=rf_model.fit(x_test,y_test)
y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.932140653917335
[[5042   31]
 [ 409 1002]]
              precision    recall  f1-score   support

           0       0.92      0.99      0.96      5073
           1       0.97      0.71      0.82      1411

    accuracy                           0.93      6484
   macro avg       0.95      0.85      0.89      6484
weighted avg       0.93      0.93      0.93      6484

